markdown: kramdown
highlighter: rouge
permalink: /posts/:title.html
safe: true
excerpt_separator: "<!-- more -->"

github: hiddenbomb
author: "Mortred"
email: bwgui203#gmail.com
name: "Mortred"
url: http://mortred.me
domain: mortred.me
all_categories: [
["C++", "C++开发","/posts/C++.html"], 
["linux", "Linux相关","/posts/Linux.html"],
["web", "Web建站","/posts/web.html"], 
["about", "关于","/about.html"]
]

paginate: 16
paginate_path: "posts/page:num"
timezone: Asia/Beijing

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
